SIM_DURATION 3
N_NANO_SECS 50000
NOF_WORKERS 24
NOF_USERS 50
NOF_TABLE_SEATS 20
MAX_PORZIONI_PRIMI 100
MAX_PORZIONI_SECONDI 100
AVG_REFILL_PRIMI 50
AVG_REFILL_SECONDI 50
OVERLOAD_THRESHOLD 100
AVG_SRVC_PRIMI 1
AVG_SRVC_SECONDI 1
AVG_SRVC_COFFEE 1
AVG_SRVC_CASSA 1
PRICE_PRIMI 1
PRICE_SECONDI 1
PRICE_COFFEE 1