SIM_DURATION 10
N_NANO_SECS 50000
NOF_WORKERS 4
NOF_USERS 50
NOF_TABLE_SEATS 5
MAX_PORZIONI_PRIMI 2
MAX_PORZIONI_SECONDI 2
AVG_REFILL_PRIMI 0
AVG_REFILL_SECONDI 0
OVERLOAD_THRESHOLD 2
AVG_SRVC_PRIMI 100
AVG_SRVC_SECONDI 100
AVG_SRVC_COFFEE 100
AVG_SRVC_CASSA 100
PRICE_PRIMI 5
PRICE_SECONDI 8
PRICE_COFFEE 1